import { workoutRepo } from '@/lib/repositories/WorkoutRepo';
import catalog from '@/assets/exercises/catalog.json';

interface CatalogEntry {
  exerciseDbId: string;
  name: string;
  muscleGroup?: string | null;
  equipment?: string | null;
  category?: string | null;
  musclesPrimary?: string[];
  musclesSecondary?: string[];
  description?: string | null;
  instructions?: string[];
  tips?: string[];
  gifUrl?: string | null;
}

/**
 * One-time import of the bundled exercise catalog into SQLite. The catalog is
 * generated by `scripts/seed-exercises.mjs` from ExerciseDB v1. Media (GIFs) is
 * resolved separately (bundled asset → cached file → remote) by exerciseMedia.ts.
 */
export function seedExercisesIfEmpty() {
  if (workoutRepo.countExercises() > 0) return;
  const entries = catalog as CatalogEntry[];
  for (const e of entries) {
    workoutRepo.upsertExercise({
      id: '', // upsert dedups on exerciseDbId/serverId; empty → new localId
      exerciseDbId: e.exerciseDbId,
      name: e.name,
      nameAlternative: null,
      description: e.description ?? null,
      instructions: e.instructions ?? [],
      tips: e.tips ?? [],
      muscleGroup: e.muscleGroup ?? null,
      musclesPrimary: e.musclesPrimary ?? [],
      musclesSecondary: e.musclesSecondary ?? [],
      equipment: e.equipment ?? null,
      category: e.category ?? null,
      imageUrl: null,
      videoUrl: null,
      gifUrl: e.gifUrl ?? null,
      isCustom: false,
    });
  }
}
