import { workoutRepo } from '@/lib/repositories/WorkoutRepo';
import catalog from '@/assets/exercises/catalog.json';

interface CatalogEntry {
  exerciseDbId: string;
  name: string;
  muscleGroup?: string | null;
  equipment?: string | null;
  category?: string | null;
  musclesPrimary?: string[];
  musclesSecondary?: string[];
  description?: string | null;
  instructions?: string[];
  tips?: string[];
  gifUrl?: string | null;
}

/**
 * Import the bundled exercise catalog into SQLite. The catalog is generated by
 * `scripts/seed-exercises.mjs` from ExerciseDB v1 (deduped by exerciseDbId).
 * Media (GIFs) is resolved separately (bundled asset → cached file → remote) by
 * exerciseMedia.ts.
 *
 * Rebuilds the seeded set when the DB is empty, *duplicate-bloated* (an earlier
 * bug seeded 60 copies of each exercise), or stale (fewer distinct exercises
 * than the current catalog). Custom exercises are preserved.
 */
export function seedExercisesIfEmpty() {
  const entries = catalog as CatalogEntry[];
  const total = workoutRepo.countSeededExercises();
  const distinct = workoutRepo.countDistinctSeededExercises();
  const polluted = total !== distinct; // duplicate exerciseDbId rows present
  const stale = distinct < entries.length;
  if (total > 0 && !polluted && !stale) return;

  if (total > 0) workoutRepo.deleteSeededExercises();

  for (const e of entries) {
    workoutRepo.upsertExercise({
      id: '', // upsert dedups on exerciseDbId/serverId; empty → new localId
      exerciseDbId: e.exerciseDbId,
      name: e.name,
      nameAlternative: null,
      description: e.description ?? null,
      instructions: e.instructions ?? [],
      tips: e.tips ?? [],
      muscleGroup: e.muscleGroup ?? null,
      musclesPrimary: e.musclesPrimary ?? [],
      musclesSecondary: e.musclesSecondary ?? [],
      equipment: e.equipment ?? null,
      category: e.category ?? null,
      imageUrl: null,
      videoUrl: null,
      gifUrl: e.gifUrl ?? null,
      isCustom: false,
    });
  }
}
