import { workoutRepo } from '@/lib/repositories/WorkoutRepo';
import { getMeta, setMeta } from '@/lib/db';
import catalog from '@/assets/exercises/catalog.json';
// Hand-curated exercises that aren't in ExerciseDB (machines + a few popular staples). Kept in
// a separate file with stable `hale-*` ids so they're never clobbered when `scripts/seed-
// exercises.mjs` regenerates catalog.json, and they upsert/prune alongside it.
import extra from '@/assets/exercises/extra.json';

/**
 * Bump when catalog.json *content* changes in a way that should reach existing installs
 * even though the row count is the same (renamed/de-baked exercises, new metadata). The
 * count-based `stale` check only catches growth, so this forces an in-place re-upsert.
 */
const SEED_VERSION = '2026-06-06-curated-catalog-v1';

interface CatalogEntry {
  exerciseDbId: string;
  name: string;
  muscleGroup?: string | null;
  equipment?: string | null;
  category?: string | null;
  musclesPrimary?: string[];
  musclesSecondary?: string[];
  description?: string | null;
  instructions?: string[];
  tips?: string[];
  gifUrl?: string | null;
  /** Attachment baked into the source name (Rope, V-Bar, …); structured for the picker. */
  attachment?: string | null;
}

/**
 * Import the bundled exercise catalog into SQLite. The catalog is generated by
 * `scripts/seed-exercises.mjs` from ExerciseDB v1 (deduped by exerciseDbId).
 * Media (GIFs) is resolved separately (bundled asset → cached file → remote) by
 * exerciseMedia.ts.
 *
 * Rebuilds the seeded set when the DB is empty, *duplicate-bloated* (an earlier
 * bug seeded 60 copies of each exercise), or stale (fewer distinct exercises
 * than the current catalog). Custom exercises are preserved.
 *
 * The rebuild upserts **in place** (keyed on exerciseDbId), so each seeded exercise
 * keeps its localId across the rebuild — the templates and logged sessions that
 * reference those localIds survive a catalog refresh/growth. Entries the catalog
 * dropped are pruned afterward. The one exception is a duplicate-bloated DB (the
 * legacy bug), which can't be repaired in place and is wiped + rebuilt fresh.
 */
export function seedExercisesIfEmpty() {
  const entries = [...(catalog as CatalogEntry[]), ...(extra as CatalogEntry[])];
  const total = workoutRepo.countSeededExercises();
  const distinct = workoutRepo.countDistinctSeededExercises();
  const polluted = total !== distinct; // duplicate exerciseDbId rows present
  const stale = distinct < entries.length;
  const versionChanged = getMeta('exerciseSeedVersion') !== SEED_VERSION;
  if (total > 0 && !polluted && !stale && !versionChanged) return;

  if (polluted) workoutRepo.deleteSeededExercises();

  for (const e of entries) {
    workoutRepo.upsertExercise({
      id: '', // upsert dedups on exerciseDbId → existing row keeps its localId
      exerciseDbId: e.exerciseDbId,
      name: e.name,
      nameAlternative: null,
      description: e.description ?? null,
      instructions: e.instructions ?? [],
      tips: e.tips ?? [],
      muscleGroup: e.muscleGroup ?? null,
      musclesPrimary: e.musclesPrimary ?? [],
      musclesSecondary: e.musclesSecondary ?? [],
      equipment: e.equipment ?? null,
      category: e.category ?? null,
      imageUrl: null,
      videoUrl: null,
      gifUrl: e.gifUrl ?? null,
      isCustom: false,
    });
  }

  // Drop any seeded rows the catalog no longer ships (skip after a full wipe — nothing to prune).
  if (!polluted) workoutRepo.pruneSeededExercisesNotIn(entries.map((e) => e.exerciseDbId));
  setMeta('exerciseSeedVersion', SEED_VERSION);
}
